WHENEVER SQLERROR EXIT SQL.SQLCODE
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET DEFINE OFF

PROMPT Cleaning APPUSER19 objects...
ALTER SESSION SET CURRENT_SCHEMA = APPUSER19;

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW VW_EXP_TEST_19';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE PKG_EXP_TEST_19';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE PR_EXP_TEST_19';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION FN_EXP_TEST_19';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE TP_EXP_TEST_19 FORCE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

PROMPT Cleaning APPUSER19_2 objects...
ALTER SESSION SET CURRENT_SCHEMA = APPUSER19_2;

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW VW_EXP_TEST_19_2';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE PKG_EXP_TEST_19_2';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE PR_EXP_TEST_19_2';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION FN_EXP_TEST_19_2';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE TP_EXP_TEST_19_2 FORCE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

PROMPT Cleanup complete.
EXIT
