CREATE OR REPLACE PACKAGE APPUSER19_2.PKG_EXP_TEST_19_2 AS
  FUNCTION GET_STATUS RETURN NUMBER;
  PROCEDURE ADD_ROW(P_NOTE IN VARCHAR2);
END PKG_EXP_TEST_19_2;
/
show errors PACKAGE APPUSER19_2.PKG_EXP_TEST_19_2

CREATE OR REPLACE PACKAGE BODY APPUSER19_2.PKG_EXP_TEST_19_2 AS
  FUNCTION GET_STATUS RETURN NUMBER IS
  BEGIN
    RETURN 1;
  END GET_STATUS;

  PROCEDURE ADD_ROW(P_NOTE IN VARCHAR2) IS
  BEGIN
    NULL;
  END ADD_ROW;
END PKG_EXP_TEST_19_2;
/
show errors

