WHENEVER SQLERROR EXIT SQL.SQLCODE
SET SERVEROUTPUT ON
SET FEEDBACK ON
SET DEFINE OFF

PROMPT Validating target schemas...
DECLARE
  l_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO l_count FROM all_users WHERE username = 'APPUSER19';
  IF l_count = 0 THEN
    RAISE_APPLICATION_ERROR(-20001, 'Schema APPUSER19 not found.');
  END IF;

  SELECT COUNT(*) INTO l_count FROM all_users WHERE username = 'APPUSER19_2';
  IF l_count = 0 THEN
    RAISE_APPLICATION_ERROR(-20002, 'Schema APPUSER19_2 not found.');
  END IF;
END;
/

PROMPT Recreating objects in APPUSER19...
ALTER SESSION SET CURRENT_SCHEMA = APPUSER19;

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW VW_EXP_TEST_19';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE PKG_EXP_TEST_19';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE PR_EXP_TEST_19';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION FN_EXP_TEST_19';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE TP_EXP_TEST_19 FORCE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN
      RAISE;
    END IF;
END;
/

CREATE OR REPLACE VIEW VW_EXP_TEST_19 AS
SELECT 1 AS ID, 'APPUSER19' AS NOTE, SYSDATE AS CREATED_AT
FROM dual;

BEGIN
  EXECUTE IMMEDIATE
    'GRANT SELECT ON VW_EXP_TEST_19 TO ' || SYS_CONTEXT('USERENV', 'SESSION_USER');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-1749, -1031) THEN
      RAISE;
    END IF;
END;
/

CREATE OR REPLACE TYPE TP_EXP_TEST_19 AS OBJECT (
  ID NUMBER,
  NOTE VARCHAR2(200 CHAR),
  MEMBER FUNCTION RENDER RETURN VARCHAR2
);
/

CREATE OR REPLACE TYPE BODY TP_EXP_TEST_19 AS
  MEMBER FUNCTION RENDER RETURN VARCHAR2 IS
  BEGIN
    RETURN TO_CHAR(ID) || ':' || NOTE;
  END RENDER;
END;
/

CREATE OR REPLACE FUNCTION FN_EXP_TEST_19
  RETURN VARCHAR2
IS
BEGIN
  RETURN 'APPUSER19:OK';
END;
/

CREATE OR REPLACE PROCEDURE PR_EXP_TEST_19 (
  P_NOTE IN VARCHAR2 DEFAULT 'row from PR_EXP_TEST_19'
)
IS
BEGIN
  NULL;
END;
/

CREATE OR REPLACE PACKAGE PKG_EXP_TEST_19 AS
  FUNCTION GET_STATUS RETURN NUMBER;
  PROCEDURE ADD_ROW(P_NOTE IN VARCHAR2);
END PKG_EXP_TEST_19;
/

CREATE OR REPLACE PACKAGE BODY PKG_EXP_TEST_19 AS
  FUNCTION GET_STATUS RETURN NUMBER IS
  BEGIN
    RETURN 1;
  END GET_STATUS;

  PROCEDURE ADD_ROW(P_NOTE IN VARCHAR2) IS
  BEGIN
    NULL;
  END ADD_ROW;
END PKG_EXP_TEST_19;
/

PROMPT Recreating objects in APPUSER19_2...
ALTER SESSION SET CURRENT_SCHEMA = APPUSER19_2;

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW VW_EXP_TEST_19_2';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE PKG_EXP_TEST_19_2';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE PR_EXP_TEST_19_2';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION FN_EXP_TEST_19_2';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE TP_EXP_TEST_19_2 FORCE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN
      RAISE;
    END IF;
END;
/

CREATE OR REPLACE VIEW VW_EXP_TEST_19_2 AS
SELECT 2 AS ID, 'APPUSER19_2' AS NOTE, SYSDATE AS CREATED_AT
FROM dual;

BEGIN
  EXECUTE IMMEDIATE
    'GRANT SELECT ON VW_EXP_TEST_19_2 TO ' || SYS_CONTEXT('USERENV', 'SESSION_USER');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-1749, -1031) THEN
      RAISE;
    END IF;
END;
/

CREATE OR REPLACE TYPE TP_EXP_TEST_19_2 AS OBJECT (
  ID NUMBER,
  NOTE VARCHAR2(200 CHAR),
  MEMBER FUNCTION RENDER RETURN VARCHAR2
);
/

CREATE OR REPLACE TYPE BODY TP_EXP_TEST_19_2 AS
  MEMBER FUNCTION RENDER RETURN VARCHAR2 IS
  BEGIN
    RETURN TO_CHAR(ID) || ':' || NOTE;
  END RENDER;
END;
/

CREATE OR REPLACE FUNCTION FN_EXP_TEST_19_2
  RETURN VARCHAR2
IS
BEGIN
  RETURN 'APPUSER19_2:OK';
END;
/

CREATE OR REPLACE PROCEDURE PR_EXP_TEST_19_2 (
  P_NOTE IN VARCHAR2 DEFAULT 'row from PR_EXP_TEST_19_2'
)
IS
BEGIN
  NULL;
END;
/

CREATE OR REPLACE PACKAGE PKG_EXP_TEST_19_2 AS
  FUNCTION GET_STATUS RETURN NUMBER;
  PROCEDURE ADD_ROW(P_NOTE IN VARCHAR2);
END PKG_EXP_TEST_19_2;
/

CREATE OR REPLACE PACKAGE BODY PKG_EXP_TEST_19_2 AS
  FUNCTION GET_STATUS RETURN NUMBER IS
  BEGIN
    RETURN 1;
  END GET_STATUS;

  PROCEDURE ADD_ROW(P_NOTE IN VARCHAR2) IS
  BEGIN
    NULL;
  END ADD_ROW;
END PKG_EXP_TEST_19_2;
/

PROMPT Setup complete.
EXIT
