CREATE OR REPLACE TYPE APPUSER19.TP_EXP_TEST_19 AS OBJECT (
  ID NUMBER,
  NOTE VARCHAR2(200 CHAR),
  MEMBER FUNCTION RENDER RETURN VARCHAR2
);
/
CREATE OR REPLACE TYPE BODY APPUSER19.TP_EXP_TEST_19 AS
  MEMBER FUNCTION RENDER RETURN VARCHAR2 IS
  BEGIN
    RETURN TO_CHAR(ID) || ':' || NOTE;
  END RENDER;
END;
/
